# Generated by Django 5.0 on 2023-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Interesting'), (3, 'Good'), (4, 'Importat'), (5, 'Urgent')], default=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proccessing the business model'), (2, 'Desiging the user interaction'), (3, 'Creating prototipe app'), (4, 'Adjusting details'), (5, 'Deploying version 1'), (6, 'Improving Performance and adding new Features')], default=1),
        ),
    ]
