# Generated by Django 5.0 on 2023-12-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_project_importance_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Not started yet'), (2, 'Working on it'), (3, 'Waiting feed back'), (4, 'Completed')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='progress.project')),
            ],
            options={
                'ordering': ['-created', '-status'],
                'indexes': [models.Index(fields=['-created', '-status'], name='progress_ta_created_da9ca3_idx')],
            },
        ),
    ]
