# Generated by Django 4.2 on 2023-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_projectnote_tasknote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created', '-importance', '-status']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='progress_ta_created_da9ca3_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Interesting'), (3, 'Normal'), (4, 'Importat'), (5, 'Urgent')], default=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Interesting'), (3, 'Normal'), (4, 'Importat'), (5, 'Urgent')], default=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proccessing the business model'), (2, 'Desiging the user interaction'), (3, 'Creating prototipe app'), (4, 'Adjusting details'), (5, 'Deploying version 1'), (6, 'Improving Performance and adding new Features'), (7, 'Completed')], default=1),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created', '-importance', '-status'], name='progress_ta_created_fe131f_idx'),
        ),
    ]
