# Generated by Django 4.2 on 2023-12-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknote',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='progress.task'),
        ),
    ]
