# Generated by Django 4.2 on 2023-12-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0006_alter_tasknote_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
