# Generated by Django 5.0 on 2023-12-15 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_alter_projectnote_user_alter_tasknote_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectnote',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='tasknote',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='projectnote',
            name='progress_pr_created_5afd67_idx',
        ),
        migrations.RemoveIndex(
            model_name='tasknote',
            name='progress_ta_created_373c27_idx',
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['created'], name='progress_pr_created_4512d7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknote',
            index=models.Index(fields=['created'], name='progress_ta_created_528e55_idx'),
        ),
    ]
