# Generated by Django 4.2 on 2023-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_projectnote_options_alter_tasknote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
