# Generated by Django 4.2 on 2023-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_project_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='projects'),
        ),
    ]
