# Generated by Django 4.2 on 2023-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasknote',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
