# Generated by Django 4.2 on 2023-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0013_projectnote_public_tasknote_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='esitmated_unit_time',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='finalized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
