# Generated by Django 4.2 on 2023-12-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_task_esitmated_unit_time_task_estimated_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finalized',
            new_name='completed',
        ),
    ]
